[build]
  publish = "."

[[redirects]]
  from = "/.netlify/identity/verify"
  to = "/admin/"
  status = 301
  force = true

[[redirects]]
  from = "/.netlify/identity/confirm"
  to = "/admin/"
  status = 301
  force = true
