backend:
  name: git-gateway
  branch: main

media_folder: "images"
public_folder: "/images"

publish_mode: editorial_workflow

collections:
  - name: "site"
    label: "Contenido del sitio"
    files:
      - file: "content/site.json"
        label: "Configuración y contenido"
        name: "site"
        format: "json"
        fields:
          - label: "Marca"
            name: "brand"
            widget: "object"
            fields:
              - {label: "Nombre", name: "name", widget: "string"}
              - {label: "Eslogan", name: "slogan", widget: "string"}
              - {label: "WhatsApp", name: "phone", widget: "string"}
              - {label: "Instagram (URL)", name: "instagram", widget: "string"}
              - {label: "Email", name: "email", widget: "string"}
              - {label: "Dirección", name: "address", widget: "string"}

          - label: "Hero"
            name: "hero"
            widget: "object"
            fields:
              - {label: "Título (línea 1)", name: "title", widget: "string"}
              - {label: "Título (acento)", name: "title_accent", widget: "string"}
              - {label: "Descripción (Markdown permitido)", name: "description", widget: "text"}
              - {label: "Imagen", name: "image", widget: "image"}

          - label: "Servicios"
            name: "services"
            widget: "list"
            field: {label: "Servicio", name: "item", widget: "string"}

          - label: "Productos"
            name: "products"
            widget: "list"
            fields:
              - {label: "Título", name: "title", widget: "string"}
              - {label: "Descripción", name: "desc", widget: "text"}
              - {label: "Precio", name: "price", widget: "string"}
              - {label: "Imagen", name: "image", widget: "image"}

          - label: "Galería"
            name: "gallery"
            widget: "list"
            field: {label: "Imagen", name: "image", widget: "image"}